apiVersion: v1
kind: Service
metadata:
  name: secscan-db-rw-nodeport
  namespace: secscan
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: secscan-db
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30437
