apiVersion: v1
kind: Service
metadata:
  name: fathometer-db-rw-nodeport
  namespace: fathometer
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: fathometer-db
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30437
